version: '3.5'
services:
  minio:
    build: minio
    command: server --console-address ":9001" /finance_data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "83:9000"
      - "84:9001"
    networks:
      - finance_ntwrk
  db:
    build: postgresql
    image: finance_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - finance_ntwrk
  pgadmin:
    build: pgadmin
    image: finance_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - finance_ntwrk
  swagger-ui:
    build: swagger-ui
    image: finance_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - finance_ntwrk


  account-scheduler-service:
    build: account-scheduler-service
    image: finance_account-scheduler-service:1.0.0
    networks:
      - finance_ntwrk
    depends_on:
      - db
  account-service:
    build: account-service
    image: finance_account-service:1.0.0
    networks:
      - finance_ntwrk
    depends_on:
      - db
  user-service:
    build: user-service
    image: finance_user-service:1.0.0
    networks:
      - finance_ntwrk
    depends_on:
      - db
  classifier-service:
    build: classifier-service
    image: finance_classifier-service:1.0.0
    networks:
      - finance_ntwrk
    depends_on:
      - db
  report-service:
    build: report-service
    image: finance_report-service:1.0.0
    networks:
      - finance_ntwrk
    depends_on:
      - db
  mail-service:
    build: mail-service
    image: finance_mail-service:1.0.0
    networks:
      - finance_ntwrk
  proxy:
    build: proxy
    image: finance_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - finance_ntwrk
    depends_on:
      - account-scheduler-service
      - account-service
      - user-service
      - classifier-service
      - report-service
      - swagger-ui
      - pgadmin
      - mail-service
networks:
    finance_ntwrk:
      name: finance_ntwrk