openapi: 3.0.0
info:
  version: 1.0.0
  title: Управление личными финансами
  contact:
    name: ITAcademy
    url: http://it-academy.by

servers:
  - url: http://{host}:{port}
    description: custom server
    variables:
      host:
        description: host name
        default: localhost
      port:
        description: port value
        default: "8080"

tags:
  - name: "Email Scheduler"
    description: "Ежемесячный отчёт по email"

paths:
  /api/v1/scheduler/mail/report:
    post:
      tags:
        - "Email Scheduler"
      summary: "Подписаться на ежемесячный отчёт по email"
      requestBody:
        $ref: "#/components/requestBodies/RequestBody"
      responses:
        '201':
          description: Подписка оформлена успешно
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
          
    delete:
      tags:
        - "Email Scheduler"
      summary: "Отписаться от ежемесячного отчёта по email"
      responses:
        '204':
          description: Подписка успешно удалена
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'

components:
  requestBodies:
    RequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/emailAndType'

  responses:
    Bad_Request:
      description: Запрос некорректен. Сервер не может обработать запрос
      content:
        application/json:
          schema:
            oneOf:
              - type: array
                items:
                  $ref: '#/components/schemas/t_single_error_response'
          examples:
            t_single_error_response:
              value:
                - logref: error
                  message:  Запрос содержит некорретные данные. Измените запрос и отправьте его ещё раз
    Unauthorized:
      description: Для выполнения запроса на данный адрес требуется передать токен авторизации
    Forbidden:
      description: Данному токенту авторизации запрещено выполнять запрос на данный адрес
    Internal_Server_Error:
      description: Внутренняя ошибка сервера. Сервер не смог корректно обработать запрос
      content:
        applicaion/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/t_single_error_response'
          example:
            - logref: error
              message:  Сервер не смог корректно обработать запрос. Пожалуйста обратитесь к администратору
  schemas:
    emailAndType:
      type: object
      description: Email and report type
      properties:
        email:
          type: string
        report_type:
          type: string
          
    t_single_error_response:
      type: object
      description: Ошибка. Содержит общее описание ошибки
      required:
        - logref
        - message
      properties:
        logref:
          type: string
          description: Тип ошибки
          example: error
        message:
          description: Сообщение ошибки
          type: string
          example: Запрос содержит некорретные данные. Измените запрос и отправьте его ещё раз