spring:
  datasource:
    driver-class-name: "${spring.datasource.driver-class-name}"
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"

minio:
  url : "${minio.url}"
  bucket : "${minio.bucket}"
  access-key : "${minio.access-key}"
  secret-key : "${minio.secret-key}"

urls:
  account: http://account-service:8080/account
  operation_backend: http://account-service:8080/backend/operation
  account_backend: http://account-service:8080/backend/account
  currency_backend: http://classifier-service:8080/backend/classifier/currency
  category_backend: http://classifier-service:8080/backend/classifier/operation/category

font_name: Calibri
default_day_interval: 90