spring:
  datasource:
    driver-class-name: "${spring.datasource.driver-class-name}"
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"

account_url : http://account-service:8080/account
operation_backend_url : http://account-service:8080/backend/operation
account_backend_url : http://account-service:8080/backend/account
classifier_currency_backend_url : http://classifier-service:8080/backend/classifier/currency
classifier_category_backend_url : http://classifier-service:8080/backend/classifier/operation/category

font_name : Calibri
default_day_interval : 90

