spring:
  mail:
    host : smtp.mail.ru
    port : 465
    username : "${email.login}"
    password : "${email.password}"
    protocol : smtps
    from : "${email.login}"
    auth : true

urls:
  report: http://report-service:8080/report/%s/export