spring:
  datasource:
    driver-class-name: "${spring.datasource.driver-class-name}"
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
  mvc:
    quartz:
      job-store-type: jdbc
      jdbc:
        initialize-schema: never
        platform: postgres
      properties:
        "org.quartz.jobStore.driverDelegateClass": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
        "org.quartz.jobStore.tablePrefix": "quartz.QRTZ_"

urls:
  account: http://account-service:8080/account
  currency_backend: http://classifier-service:8080/backend/classifier/currency
  category_backend: http://classifier-service:8080/backend/classifier/operation/category
