spring:
  datasource:
    driver-class-name: "${spring.datasource.driver-class-name}"
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"

default_day_interval : 90

#classifier_currency_url : http://classifier-service:8080/backend/classifier/currency
#classifier_category_url : http://classifier-service:8080/backend/classifier/operation/category

server:
  port : 8082

classifier_currency_url : http://localhost:8080/backend/classifier/currency
classifier_category_url : http://localhost:8080/backend/classifier/operation/category