spring:
  datasource:
    driver-class-name: "${spring.datasource.driver-class-name}"
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"

classifier_currency_url : http://localhost:8081/backend/classifier/currency
classifier_category_url : http://localhost:8081/backend/classifier/operation/category